[package]
name = "project1"
version = "0.1.0"
edition = "2021"

[dependencies]
keos = { path ="../../keos" }
bitflags = "1.2.1"

[build-dependencies]
simple_fs = { path = "../../fs/simple_fs" }

[features]
default = ["smp"]
smp = ["keos/smp"]