[package]
name = "abyss"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
spin_lock = { path = "../spin_lock" }
num_enum = { version = "0.5", default-features=false }

[features]
default = []
smp = ["spin_lock/smp"]